test 2

diff --git a/.github/workflows/integration-test.yml b/.github/workflows/integration-test.yml
--- a/.github/workflows/integration-test.yml
+++ b/.github/workflows/integration-test.yml
@@ -1,21 +1,21 @@
-name: Integration Test with Service Container
+# name: Integration Test with Service Container
 
-on: [push]
+# on: [push]
 
-jobs:
-  test:
-    runs-on: ubuntu-latest
+# jobs:
+#   test:
+#     runs-on: ubuntu-latest
 
-    services:
-      app:
-        image: ghcr.io/${{ github.repository_owner }}/weather-app:latest
-        ports:
-          - 3000:3000
-        options: --health-cmd="curl http://localhost:3000 || exit 1" --health-interval=10s --health-timeout=5s --health-retries=5
+#     services:
+#       app:
+#         image: ghcr.io/${{ github.repository_owner }}/weather-app:latest
+#         ports:
+#           - 3000:3000
+#         options: --health-cmd="curl http://localhost:3000 || exit 1" --health-interval=10s --health-timeout=5s --health-retries=5
 
-    steps:
-      - name: Wait for service to be ready
-        run: sleep 20
+#     steps:
+#       - name: Wait for service to be ready
+#         run: sleep 20
 
-      - name: Test service response
-        run: curl http://localhost:3000
+#       - name: Test service response
+#         run: curl http://localhost:3000
